name: Deploy PondSupportBot

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PONDSUPPORTBOT_HOST }}
          username: ${{ secrets.PONDSUPPORTBOT_USER }}
          key: ${{ secrets.PONDSUPPORTBOT_SSH_KEY }}
          script: |
            /home/pondsupportbot/deploy.sh
